name: Test CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: dcodeIO/setup-node-nvm@master

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Run Jest
        run: npm test
